#!/usr/bin/env bash

set -exuo pipefail

target_dir="$(realpath target)"

on_exit() {
	cd /
	[ -z "${tmp_dir-}" ] || rm -rf "$tmp_dir"
}

trap on_exit EXIT

tmp_dir="$(mktemp -d)"
cd "$tmp_dir"

git clone --depth 1 https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files.git intel-microcode
git clone --depth 1 https://gitlab.com/kernel-firmware/linux-firmware.git linux-firmware

mkdir -p kernel/x86/microcode
iucode_tool --write-to=kernel/x86/microcode/GenuineIntel.bin intel-microcode/intel-ucode
cat linux-firmware/amd-ucode/microcode_amd*.bin > kernel/x86/microcode/AuthenticAMD.bin

bsdtar --uid 0 --gid 0 -cf - kernel | bsdtar -cf - --format=newc @- > "$target_dir/ucode.cpio"
