[package]
name = "feos_client"
version = "0.1.0"
edition = "2018"

[dependencies]
tonic = "0.5"
tokio = { version = "1", features = ["full"] }
prost = "0.8"
prost-types = "0.8"
structopt = "0.3"
tokio-stream = "0.1"
futures = "0.3"

[build-dependencies]
tonic-build = "0.5"

