[package]
name = "feos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"

[dependencies]
futures = "0.3.29"
netlink-packet-route = "0.19.0"
rtnetlink = "0.14.0"

nix = { version = "0.28.0", features = ["mount", "user"] }
tokio = { version = "1.35.0", features = ["full", "macros", "rt-multi-thread"] }
log = "0.4.20"
simple_logger = "4.3.0"
tonic = "0.11"
prost = "0.12"
bitflags = "2.5.0"
uuid = { version = "1.8.0", features = ["v4"] }
oci-distribution = "0.11.0"
serde = "1.0.197"
serde_json = "1.0.115"
api_client = { version = "0.1.0", git = "https://github.com/cloud-hypervisor/cloud-hypervisor"  }
openssl = { version = "0.10", features = ["vendored"] }

[build-dependencies]
tonic-build = "0.11.0"