[package]
name = "feos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
futures = "0.3.29"
netlink-packet-route = "0.17.1"
rtnetlink = "0.13.1"

nix = { version = "0.27.1", features = ["mount"] }
tokio = { version = "1.34.0", features = ["full"] }
