[package]
name = "feos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"

[dependencies]
futures = "0.3.29"
netlink-packet-route = "0.17.1"
rtnetlink = "0.13.1"

nix = { version = "0.27.1", features = ["mount", "user"] }
tokio = { version = "1.35.0", features = ["full", "macros", "rt-multi-thread"] }
log = "0.4.20"
simple_logger = "4.3.0"
tonic = "0.10"
prost = "0.12"

[build-dependencies]
tonic-build = "0.10"