[package]
name = "feos-proto"
version = "0.2.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }