name: Integration Test (DHCPv6)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Python and dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip iproute2

      - name: Install test dependencies
        run: |
          if [ -f scripts/requirements.txt ]; then
            pip3 install -r scripts/requirements.txt
          fi

      - name: Run integration test (needs sudo for veth and server)
        run: sudo -E env "PATH=$PATH" cargo test --test dhcpv6_client_integration
