name: FeOS Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Protobuf Compiler
      run: sudo apt-get update && sudo apt-get install protobuf-compiler -y

    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Run Tests
      run: make test
