name: FeOS Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Protobuf Compiler
      run: sudo apt-get update && sudo apt-get install protobuf-compiler -y

    - name: Check Out Repo
      uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: Check Format
      run: cargo fmt --check

    - name: Run Tests
      run: make test
