name: FeOS Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Protobuf Compiler and Musl
      run: sudo apt-get update && sudo apt-get install musl-tools musl-dev protobuf-compiler -y

    - name: Install Rust Toolchain
      run: rustup component add clippy && rustup component add rustfmt && rustup target add x86_64-unknown-linux-musl

    - name: Set up cargo cache
      uses: actions/cache@v4
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Run Tests
      run: make test
